### ISSUE TITLE
"UpdateAdministrationRoleViewAction" doesn't check if provided role is found

### ISSUE THREAD

**Issue by diimpp** [Sylius/RbacPlugin#58]
https://github.com/Sylius/RbacPlugin/blob/master/src/Action/UpdateAdministrationRoleViewAction.php#L50

Should throw `NotFoundException` in case it's not there.

**Comment by Zales0123** [comment]
Agreed 👍 Are you willing to open a PR with this fix?

**Comment by diimpp** [comment]
@Zales0123 Yes, I'm currently doing my first integration of the plugin, I can take on the issues, once I will be done.

**Comment by bartoszpietrzak1994** [comment]
Hi Dmitri!

Thank you for pointing out this issue and we all appreciate your will to help us with fixing it. However, since we want to stabilize the plugin as fast as possible, I've managed to open a PR with the fix.
