### ISSUE TITLE
"AdministrationRoleTrait" should be "AdministrationRoleAwareTrait" in accordence with interface

### ISSUE THREAD

**Issue by diimpp** [Sylius/RbacPlugin#60]
https://github.com/Sylius/RbacPlugin/blob/master/src/Entity/AdministrationRoleTrait.php#L10

**Comment by tom10271** [comment]
I tried to install this plugin today and followed the master readme.md. The latest version released is 0.2.1, if developer follows the readme.md in master he will not be able to install it successfully. Although it is a small issue yet it is still a bit confusing. It might be a good idea to release a new version
