### ISSUE TITLE
An exception has been thrown during the rendering of a template ("Resource "sylius_rbac.administration_role" does not exist in alias: sylius_rbac.administration_role

### ISSUE THREAD

**Issue by parthajudiyap** [Sylius/RbacPlugin#75]
(5/5) RuntimeError
An exception has been thrown during the rendering of a template ("Resource "sylius_rbac.administration_role" does not exist in alias: sylius_rbac.administration_role
only: ['index']
section: admin
templates: SyliusAdminBundle:Crud
grid: sylius_rbac_administration_role
redirect: update
(which is being imported from "/home/gomataseva72p/public_html/acme/vendor/sylius/rbac-plugin/src/Resources/config/routing/admin_routing.yml"). Make sure there is a loader supporting the "sylius.resource" type.").

sylius_rbac_administration_role:
    resource: |
        alias: sylius_rbac.administration_role
        only: ['index']
        section: admin
        templates: SyliusAdminBundle:Crud
        grid: sylius_rbac_administration_role
        redirect: update
    type: sylius.resource

sylius_rbac_admin_administration_role_create_view:
    path: /administration-roles/new
    methods: [GET]
    defaults:
        _controller: Sylius\RbacPlugin\Action\CreateAdministrationRoleViewAction

sylius_rbac_admin_administration_role_create:
    path: /administration-roles/new
    methods: [PUT, PATCH]
    defaults:
        _controller: Sylius\RbacPlugin\Action\CreateAdministrationRoleAction

sylius_rbac_admin_administration_role_update_view:
    path: /administration-roles/{id}/update
    methods: [GET]
    defaults:
        _controller: Sylius\RbacPlugin\Action\UpdateAdministrationRoleViewAction

sylius_rbac_admin_administration_role_update:
    path: /administration-roles/{id}/update
    methods: [POST]
    defaults:
        _controller: Sylius\RbacPlugin\Action\UpdateAdministrationRoleAction

**Comment by Zales0123** [comment]
Have you installed the plugin properly? Do you have `@SyliusRbacPlugin/Resources/config/config.yml` imported?

**Comment by Zales0123** [comment]
I hope you've resolved your problem, feel free to reopen if you still think there is a bug :)
