### ISSUE TITLE
 [Semantical Error] The annotation "@MappedSuperclass" in class App\Entity\User\     AdminUser was never imported. Did you maybe forget to add a "use" statement for      this annotation?

### ISSUE THREAD

**Issue by Den-Uchiwa** [Sylius/RbacPlugin#86]
Hello, i try to install RbacPlugin i follow step per step but when i try to migrate i have this error(step 6):
 [Semantical Error] The annotation "@MappedSuperclass" in class App\Entity\User\  
  AdminUser was never imported. Did you maybe forget to add a "use" statement for  
   this annotation?
what i need to write for leave this error?

**Comment by Zales0123** [comment]
Hello @Den-Uchiwa, you should import this annotation. Check out the mentioned PR that introduce missing imports into the README :)
